### ISSUE TITLE
Readme generated by ``dtool readme interactive`` looses indentation

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-create#8]
Current output:

```
---
description: Dataset description
project: Project name
confidential: false
personally_identifiable_information: false
owners:
- name: Your Name
  email: olssont@nbi.ac.uk
  username: olssont
creation_date: 2017-10-23
# links:
#  - http://doi.dx.org/your_doi
#  - http://github.com/your_code_repository
# budget_codes:
#  - E.g. CCBS1H10S
```

Expected:

```
---
description: Dataset description
project: Project name
confidential: false
personally_identifiable_information: false
owners:
  - name: Your Name
    email: olssont@nbi.ac.uk
    username: olssont
creation_date: 2017-10-23
# links:
#  - http://doi.dx.org/your_doi
#  - http://github.com/your_code_repository
# budget_codes:
#  - E.g. CCBS1H10S
```
